project:
  type: website

website:
  title: "Ravi Brenner"
  navbar:
    right:
      - text: "Home"
        href: index.html
      - text: "Resume"
        href: resume.html
      - text: "Publications"
        href: publications.html
format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css



