---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(p8105.datasets)
library(tidyverse)
library(plotly)

data("instacart")

```

Column {data-width=500}
-----------------------------------------------------------------------

### Number of items ordered by department

```{r, echo = FALSE}
instacart |>
  count(department) |>
  mutate(department = fct_reorder(department, n)) |>
  plot_ly(x = ~n, y = ~department, type = "bar") |>
  layout(yaxis = list(title = 'Department'),
         xaxis = list(title = "Number of items"))
```

Column {data-width=500}
-----------------------------------------------------------------------

### Orders by hour of day and time of day

```{r, echo=FALSE}
instacart |>
  filter(!duplicated(order_id)) |>
  mutate(order_dow = factor(order_dow,
                            labels = c("Sunday","Monday",
                                       "Tuesday","Wednesday",
                                       "Thursday","Friday",
                                       "Saturday"))) |>
  group_by(order_hour_of_day,order_dow) |>
  count()  |>
  plot_ly(x = ~order_hour_of_day, 
          y = ~n,
          color = ~order_dow,
          type = "scatter",
          mode = "colors") |>
  layout(xaxis = list(title = "Hour of day"),
         yaxis = list(title = "Number of orders" ))

```

### Order size histogram

```{r}
instacart |>
  group_by(order_id) |>
  summarize(order_size = max(add_to_cart_order)) |>
  plot_ly(x = ~order_size, type = "histogram") |>
  layout(xaxis = list(title = "Order size"))
```

