---
title: "Publications"
format: html
---

-   **Brenner IR**, Flanagan CF, Penazzato M, Webb KA, Horsfall SB, Hyle EP, Abrams E, Bacha J, Neilan AM, Collins IJ, Desmonde S, Crichton S, Davies MA, Freedberg KA, Ciaranello AL. Cost-effectiveness of viral load testing for transitioning antiretroviral therapy-experienced children to dolutegravir in South Africa: a modelling analysis. The Lancet Global Health. 2024;12(12):e2068-e2079. doi:10.1016/S2214-109X(24)00381-4

-   Kalkowska DA, Badizadegan K, Routh JA, Burns CC, Rosenberg ES, **Brenner IR**, Zucker JR, Langdon-Embry M, Thompson KM. Modeling undetected poliovirus circulation following the 2022 outbreak in the United States. Expert Review of Vaccines. 2024;23(1):186-195. doi:10.1080/14760584.2023.2299401.

-   Neilan AM, Ufio OL, **Brenner IR**, Flanagan CF, Shebl FM, Hyle EP, Freedberg KA, Ciaranello AL, Patel K. Projected Life Expectancy for Adolescents With HIV in the US. JAMA Health Forum. 2024;5(5):e240816. doi:10.1001/jamahealthforum.2024.0816.

-   Mitchell EC, Nguyen T, Boulais M, **Brenner IR**, Dorabawila V, Hoen R, Li Y, Cavazos M, Levine B, Anderson BJ, Battles H, Brissette I, Backenson B, Lutterloh E, Bauer UE, Rosenberg ES. Home testing for SARS-CoV-2 and impact on surveillance in New York State. Annals of Epidemiology. Published online November 22, 2023. doi:10.1016/j.annepidem.2023.11.009.

-   **Brenner IR**, Simpson KN, Flanagan CF, Dark T, Dooley M, Agwu AL, Koay WLA, Freedberg KA, Ciaranello AL, Neilan AM. Projecting the clinical and economic impacts of changes to HIV care among adolescents and young adults in the US: lessons from the COVID-19 pandemic. J Pediatric Infect Dis Soc. Published online November 14, 2023:piad102. doi:10.1093/jpids/piad102.

-   Thompson KM, Kalkowska DA, Routh JA, **Brenner IR**, Rosenberg ES, Zucker JR, Langdon-Embry M, Sugerman DE, Burns CC, Badizadegan K. Modeling poliovirus transmission and responses in New York State. J Infect Dis. 2023 Aug 19:jiad355. doi: 10.1093/infdis/jiad355. Epub ahead of print. PMID: 37596838.

-   Nelson SB, Dugdale CM, **Brenner IR**, Crawford A, Bilinski A, Cosar D, Pollock NR, Ciaranello A. Prevalence and Risk Factors for School-Associated Transmission of SARS-CoV-2. JAMA Health Forum. 2023 Aug 4;4(8):e232310. doi: 10.1001/jamahealthforum.2023.2310. PMID: 37540523; PMCID: PMC10403780.

-   Nelson SB, **Brenner IR**, Homan E, Lee SB, Bongiorno C, Pollock NR, Ciaranello A. Evaluation of "Test to Return" after COVID-19 Diagnosis in a Massachusetts Public School District. J Sch Health. 2023 Jun 4. doi: 10.1111/josh.13357. Epub ahead of print. PMID: 37272202.

-   **Brenner IR**, Raizen DM, Fang-Yen C. Pharyngeal timing and particle transport defects in Caenorhabditis elegans feeding mutants. J Neurophysiol. 2022 Aug 1;128(2):302-309. doi: 10.1152/jn.00444.2021. Epub 2022 Jun 22. PMID: 35730757.