---
title: "Learning about embedding matrices using stock prices"
author: "Ravi Brenner"
format: html
categories: [projects]
draft: true
engine: jupyter
---

When you send a message to an AI model, how does it "know" what your words "mean"? It should go without saying that it is quite complicated, and the specific layers within a particular large language model (LLM) can vary a bit. I am not an expert on large language models, but I know they are a specific type of neural network. They use an architecture called a transformer and a technique called attention (this super [cool graphic](https://poloclub.github.io/transformer-explainer/) walks through some of the details).

The first step in this kind of neural network is called embedding. An embedding layer or embedding matrix allows the model to convert categorical or text-like inputs into numbers. For example, with an LLM, there may be hundreds of thousands of possible input words. With the embedding layer, the model convert each word to a list of 200 numbers (for example). Each word can then be [compared to another](https://youtu.be/wjZofJX0v4M?t=747&si=4w36iWRWXraYx7rF), so similar words will have similar lists (called vectors) in this high dimensional space.

If you're already feeling lost, don't worry. We are going to learn about embedding matrices using a simpler type of neural network called a recurrent neural network, or RNN. This is used to predict sequences of things, like stock prices over time or words in a sentence, and leverages an embedding layer to help accomplish that. If you're not interested in all the details, skip down to here to take a look at some of the results.
